inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - command_line/fixtures/bad_syntax.rb
  DisabledByDefault: true

Lint:
  Enabled: true

Lint/LiteralInCondition:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

# The cop registers too many false positives to `.should == something`
Lint/Void:
  Enabled: false
