sudo: false
language: ruby
rvm:
  - 2.0.0-p647
  - 2.1.7
  - 2.2.3
  - ruby-head
install:
  - git clone https://github.com/ruby/mspec.git ../mspec
script:
  - ../mspec/bin/mspec
branches:
  only:
    - master
