sudo: false
language: ruby
rbenv:
  - 2.1
  - 2.2
  - 2.3
  - ruby-head
install:
  - git clone https://github.com/ruby/mspec.git ../mspec
script:
  - ../mspec/bin/mspec
branches:
  only:
    - master
    - /^try/
notifications:
  email:
    on_success: change
    on_failure: change
