language: ruby
install:
  - git clone --depth 1 https://github.com/ruby/mspec.git ../mspec
script:
  - CHECK_LEAKS=true ../mspec/bin/mspec
rvm: 2.7.0
branches:
  only:
    - master
    - /^try/
notifications:
  email:
    on_success: change
    on_failure: change
