sudo: false
language: ruby
install:
  - git clone https://github.com/ruby/mspec.git ../mspec
script:
  - ../mspec/bin/mspec $MSPEC_OPTS
matrix:
  include:
    - os: osx
      rvm: 2.4.0
    - os: linux
      rvm: 2.4.0
      env: MSPEC_OPTS="-R2 -ff"
    - os: linux
      rvm: 2.2.6
    - os: linux
      rvm: 2.3.4
    - os: linux
      rvm: 2.4.0
      env: CHECK_LEAKS=true
    - os: linux
      rvm: ruby-head
branches:
  only:
    - master
    - /^try/
notifications:
  email:
    on_success: change
    on_failure: change
