sudo: false
addons:
  apt:
    packages:
    - libgmp10
language: ruby
rvm:
  - 2.0.0-p648
  - 2.1.8
  - 2.2.4
  - ruby-head
install:
  - git clone https://github.com/ruby/mspec.git ../mspec
script:
  - ../mspec/bin/mspec
branches:
  only:
    - master
