---
version: "{build}"
clone_depth: 5
install:
  - SET PATH=C:\Ruby22\bin;%PATH%
  - ruby --version
  - git clone https://github.com/ruby/mspec.git ../mspec
build: off
test_script:
  - ../mspec/bin/mspec -fs
branches:
  only:
    - appveyor
